### ISSUE TITLE
Missing v2020.06 release

### ISSUE THREAD

**Issue by alanjfs** [mosra/magnum-singles#1]
Hello @mosra! Would it be possible to make a tag/release for the v2020.06 release? That would enable me to say..

```
git clone https://github.com/mosra/magnum-singles --branch v2020.06
```

..like most other Magnum repos, which would be fabulous!

**Comment by mosra** [comment]
Hi! The tags/releases are not present in this repo because I assumed people would just grab particular files and embed them in their own repos (which is how it's usually done with the [`stb_*`](https://github.com/nothings/stb) libraries, for example).

But if tags would help you, I can add them, of course -- can you tell me where are you using these so I can better understand your use case? :)

**Comment by alanjfs** [comment]
Thanks :) The usecase is simply to document which version is being used whenever I write instructions involving Magnum and cloning.

Like this one: https://gist.github.com/alanjfs/e7078b6c646cefa7e532549963d6c2fa#file-clone_magnum-ps1

For repos that don't have a tag, it means a few extra lines of `cd` and `git checkout` along with not really communicating whether the commit id being checked out is recent or old. A tag makes that less ambiguous I find.

> I assumed people would just grab particular files and embed them in their own repos

That's interesting, I assumed the files belonged together. But I do like the stb approach so that makes sense. Still though, if I were to do that, I would have no record of what version I copied into my project, so even for stb I clone the repo and keep tabs on which tag or commit I'm using so I know when/where to upgrade and can compare changes.

**Comment by mosra** [comment]
> I would have no record of what version I copied into my project

Each file has the exact commit(s) it was generated from embedded in its header -- and the changelog is just a very condensed overview of the "upstream" commit range (in this case https://github.com/mosra/corrade/compare/162d6a7d77e4940f7c05613013e1d3aa522bc8c6...61d1b58c): https://github.com/mosra/magnum-singles/blob/65805d9f9a3a3791adcd7be083501cf512e6e5ba/CorradeArrayView.h#L39

Just to avoid potential confusion -- if a project already uses Corrade or Magnum libraries, this repo has no use. Everything here is present in those libraries already, with full docs and possibly better compile times because it's not all smashed together in a single file.

Added `v2019.10` and `v2020.06` tags, although I still think cherry-picking and embedding particular commits is the better way :)

**Comment by alanjfs** [comment]
> Just to avoid potential confusion -- if a project already uses Corrade or Magnum libraries, this repo has no use.

Oh, confusion indeed. I didn't understand that. I've used it as an additional dependency to Magnum/Corrade. Will investigate why they got added in the first place.. In that case, I might not need the tags after all. :S

**Comment by alanjfs** [comment]
No, indeed. Just removing that import made nobody complain about anything missing. I must have had a brainfart. One less dependency to my projects, good stuff. :)
